### ISSUE TITLE
Aikau Maven Archetype Server side scripting not working

### ISSUE THREAD

**Issue by vincent-kali** [Alfresco/Aikau#1036]
I'm unable to run js script on server side to render a page.
To reproduce:
- deploy the aikau-sample war on a 5.1.e community alf (https://github.com/Alfresco/Aikau/blob/master/tutorial/chapters/Tutorial1.md)
- Add a custom page with js functions inside the js controler
- Load the custom page

Following error appears in log:
 2016-05-04 21:51:45,150  ERROR [extensions.webscripts.AbstractRuntime] [http-apr-8080-exec-7] Exception from executeScript - redirecting to status template error: 04040001 Failed to execute script 'org.springframework.extensions.webscripts.ResourceStore$WebApplicationStoreScriptContent@681b367e': null
 org.springframework.extensions.webscripts.WebScriptException: 04040001 Failed to execute script 'org.springframework.extensions.webscripts.ResourceStore$WebApplicationStoreScriptContent@681b367e': null
        at org.springframework.extensions.webscripts.processor.JSScriptProcessor.executeScript(JSScriptProcessor.java:217)
        at org.springframework.extensions.webscripts.AbstractWebScript.executeScript(AbstractWebScript.java:1376)
        at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:86)
        at org.springframework.extensions.webscripts.PresentationContainer.executeScript(PresentationContainer.java:70)
        at org.springframework.extensions.webscripts.LocalWebScriptRuntimeContainer.executeScript(LocalWebScriptRuntimeContainer.java:240)
        at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:378)
        at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:209)
        at org.springframework.extensions.webscripts.WebScriptProcessor.executeBody(WebScriptProcessor.java:311)
        at org.springframework.extensions.surf.render.AbstractProcessor.execute(AbstractProcessor.java:58)
        at org.springframework.extensions.surf.render.RenderService.process(RenderService.java:602)
        at org.springframework.extensions.surf.render.RenderService.processComponent(RenderService.java:475)
        at org.springframework.extensions.surf.render.RenderService.renderComponent(RenderService.java:951)
        at org.springframework.extensions.directives.AutoComponentRegionDirective.execute(AutoComponentRegionDirective.java:100)
        at freemarker.core.Environment.visit(Environment.java:389)
        at freemarker.core.UnifiedCall.accept(UnifiedCall.java:104)
        at freemarker.core.Environment.visit(Environment.java:324)
        at freemarker.core.MixedContent.accept(MixedContent.java:54)
        at freemarker.core.Environment.visit(Environment.java:324)
        at freemarker.core.Environment.invokeNestedContent(Environment.java:546)
        at freemarker.core.BodyInstruction.accept(BodyInstruction.java:56)
        at freemarker.core.Environment.visit(Environment.java:324)
        at freemarker.core.MixedContent.accept(MixedContent.java:54)
        at freemarker.core.Environment.visit(Environment.java:324)
        at freemarker.core.Macro$Context.runMacro(Macro.java:184)
        at freemarker.core.Environment.invoke(Environment.java:701)
        at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
        at freemarker.core.Environment.visit(Environment.java:324)
        at freemarker.core.MixedContent.accept(MixedContent.java:54)
        at freemarker.core.Environment.visit(Environment.java:324)
        at freemarker.core.Environment.process(Environment.java:302)
        at org.springframework.extensions.webscripts.processor.FTLTemplateProcessor.process(FTLTemplateProcessor.java:192)
        at org.springframework.extensions.webscripts.AbstractWebScript.renderTemplate(AbstractWebScript.java:946)
        at org.springframework.extensions.webscripts.DeclarativeWebScript.renderFormatTemplate(DeclarativeWebScript.java:267)
        at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:147)
        at org.springframework.extensions.webscripts.PresentationContainer.executeScript(PresentationContainer.java:70)
        at org.springframework.extensions.webscripts.LocalWebScriptRuntimeContainer.executeScript(LocalWebScriptRuntimeContainer.java:240)
        at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:378)
        at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:209)
        at org.springframework.extensions.webscripts.WebScriptProcessor.executeBody(WebScriptProcessor.java:311)
        at org.springframework.extensions.surf.render.AbstractProcessor.execute(AbstractProcessor.java:58)
        at org.springframework.extensions.surf.render.RenderService.processTemplate(RenderService.java:724)
        at org.springframework.extensions.surf.render.bean.TemplateInstanceRenderer.body(TemplateInstanceRenderer.java:142)
        at org.springframework.extensions.surf.render.AbstractRenderer.render(AbstractRenderer.java:78)
        at org.springframework.extensions.surf.render.bean.PageRenderer.body(PageRenderer.java:86)
        at org.springframework.extensions.surf.render.AbstractRenderer.render(AbstractRenderer.java:78)
        at org.springframework.extensions.surf.render.RenderService.renderPage(RenderService.java:770)
        at org.springframework.extensions.surf.mvc.PageView.dispatchPage(PageView.java:412)
        at org.springframework.extensions.surf.mvc.PageView.renderView(PageView.java:307)
        at org.springframework.extensions.surf.mvc.AbstractWebFrameworkView.renderMergedOutputModel(AbstractWebFrameworkView.java:321)
        at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:264)
        at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1216)
        at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1001)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:945)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:867)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:953)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:844)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:829)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at myPortal.AikauAuthenticationFilter.doFilter(AikauAuthenticationFilter.java:72)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1074)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2466)
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2455)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at org.springframework.extensions.webscripts.processor.JSScriptProcessor.loadScriptResource(JSScriptProcessor.java:238)
        at org.springframework.extensions.surf.processor.JSScriptWithTokensProcessor.loadScriptResource(JSScriptWithTokensProcessor.java:108)
        at org.springframework.extensions.surf.core.scripts.ScriptResourceHelper.recurseScriptImports(ScriptResourceHelper.java:155)
        at org.springframework.extensions.surf.core.scripts.ScriptResourceHelper.resolveScriptImports(ScriptResourceHelper.java:64)
        at org.springframework.extensions.webscripts.processor.JSScriptProcessor.executeScript(JSScriptProcessor.java:184)
        ... 82 more

**Comment by draperd** [comment]
Can you clarify if any of the pages that you create in the tutorial work or whether or not it is just your custom page that is not working?

**Comment by vincent-kali** [comment]
Only my custom page is not working, because some js script is embedded (not only widgets declaration). The 'resource' var seems to be null in JSScriptProcessor.loadScriptResource method.

**Comment by draperd** [comment]
I think you're going to have to describe what you mean, preferably with a code sample... what JS is embedded and where is it embedded?

**Comment by vincent-kali** [comment]
In fact I finally realize that the problem is coming from the "include" directive in server side javascript.
Classpath is pointing to WEB-INF/classes, and server side JS are placed by default outside classpath in the archetype which makes things more difficult from my point of view.
